services:
  prontocaps-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: prontocaps-backend
    container_name: prontocaps-api
    ports:
      - "8080:8080"
    environment:
      TZ: America/Sao_Paulo

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tech_challenge_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456

      # JWT
      JWT_SECRET: "a4e6a1e3b5e4f2a3c8d7b1a0c9e8d7c6b5a4e3f2a1c8d7b9a0c9e8d7c6b5a4e3"
      JWT_EXPIRATION: 7200000

    depends_on:
      - db

  db:
    image: postgres:16
    container_name: tech-challenge-postgres
    restart: always
    environment:
      POSTGRES_DB: tech_challenge_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - tech_challenge_db-data:/var/lib/postgresql/data

volumes:
  tech_challenge_db-data:
