services:
  prontocaps-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: prontocaps-backend
    container_name: prontocaps-api
    ports:
      - "8080:8080"
    environment:
      TZ: America/Sao_Paulo

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tech_challenge_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456

      # JWT
      JWT_SECRET: "troque-isto-por-uma-chave-bem-grande-com-32-ou-mais-caracteres"
      JWT_EXPIRES_MINUTES: 120

    depends_on:
      - db

  db:
    image: postgres:16
    container_name: tech-challenge-postgres
    restart: always
    environment:
      POSTGRES_DB: tech_challenge_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - tech_challenge_db-data:/var/lib/postgresql/data

volumes:
  tech_challenge_db-data:
